title: Another Site Template
url: "https://static2.ten7.com"
plugins:
    - jekyll-relative-links
    - jekyll-feed
    - jekyll-seo-tag
relative_links:
    enabled: true
    collections: true
include:
    - index.md
nav:
    - title: "Drop Down"
      is_mobile_nav_item: false
      subfolderitems:
          items:
              - title: "Page 1"
                description: "Some amazing description"
                url: "/page1.html"
              - title: "Page 2"
                description: "Something else"
                url: "/page2.html"
    - title: "Page 2"
      description: ""
      url: "/page2.html"
      is_mobile_nav_item: true
    - title: "Github"
      description: "Check out our Github"
      url: "https://github.com/ten7/static2.ten7.com"
      is_mobile_nav_item: true
      is_button: true

markdown: kramdown

collections:
    pages:
        output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - assets/_src/
    - clean-theme.gemspec
    - ansible/
    - ansible-hosts
    - ansible.cfg
    - Gemfile
    - Gemfile.lock
    - imagemin.js
    - LICENSE
    - node_modules/
    - npm-debug.log
    - package.json
    - package-lock.json
    - README.md
    - tsconfig.json
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - webpack.config.js
    - yarn.lock
